- src/store/userStore.ts
zustand 유저 정보 이름, 성별, 폰번호, 태어난 년도, 여행 스타일, 여행 테마 등 셋팅.
> Feat: zustand setting

- package-lock.json
- package.json
- src/App.tsx
- src/components/Header.tsx
- src/components/Layout.tsx
- src/components/NotFound.tsx
- src/components/icons/BackIcon.tsx
- src/index.tsx
- src/pages/Home.tsx
- src/pages/Login.tsx
- src/pages/SignUp.tsx
- src/styles/globalStyle.ts
전체적인 layout 을 적용하였고, globalstyle을 적용해 css를 리셋 시켰습니다.
또한 react-query setting과 header 회원가입 부분만 적용을 해놓았습니다.
react-router-dom 역시 임시로 세팅만 해놓은 것이라 추후 수정이 필요합니다.
> layout 디자인 및 header 임시 생성

- src/App.tsx
- src/pages/RegisterForm.tsx
- src/pages/RegisterPhoneNumber.tsx
- src/pages/RegisterTripStyle.tsx
- src/pages/ResgiterName.tsx
- src/pages/SignUp.tsx
register 관련 page들 router에 연결했습니다.
> Feat: register 관련 routing 추가

- src/pages/RegisterTripStyle.tsx
여행 선호 설정 태그 내용은 추후에 수정.
회원가입 중 선호도 선택 화면 '__님' 문자 깨짐 수정 완료.
> Design: 태그항목 20개로 정정& '__님' 문자 깨짐 수정

- src/App.tsx
- src/api/user.ts
- src/index.tsx
- src/mocks/handler.ts
- src/pages/Login.tsx
- src/pages/OauthGoogle.tsx
- src/utils/constants.ts
- src/vite-env.d.ts
> Feat: google 간편 로그인 가완성(백엔드 테스트 필요)

- src/components/Layout.tsx
> hotfix: 홈화면 하단바 일부 페이지에서 안보이는 문제 수정

- src/pages/Home/ContentTitleContainer.tsx
- src/pages/Home/Home.tsx
- src/pages/Home/TripAvailable.tsx
- src/pages/Home/TripRecommendation.tsx
홈 헤더 배경색 회색 수정 & 타이틀 줄바꿈 위치 고정하여 수정
> 디자인 수정 : 홈 화면 헤더 배경색 회색 전체 fixed된 부분 수정. 컨텐츠 타이틀 줄바꿈 위치 조정

- src/components/Button.tsx
- src/components/Dropdown.tsx
- src/pages/RegisterTripStyle.tsx
1. 다음 버튼 border radius 수정
2. 선호도 등록 페이지 유저 이름 밑줄 친 부분 제외.
> 디자인 수정: 회원 가입 이름 등록 ~ 선호도 등록 페이지 디자인 수정 

- src/components/Layout.tsx
> fix: 로그인 여부 체크 로직 부분 수정

- src/components/HorizonBoxLayout.tsx
- src/components/SearchResultList.tsx
- src/components/triplist/TripInfiniteList.tsx
- src/hooks/bookmark/useBookmark.ts
- src/mocks/tripDetailHandler.ts
- src/model/search.ts
- src/model/trip.ts
- src/pages/Home/BookmarkContainer.tsx
- src/pages/Home/TripAvailable.tsx
- src/pages/Home/TripRecommendation.tsx
- src/pages/TripDetail/TripDetailHeader.tsx
- src/store/client/tripDetailStore.ts
북마크 기능 - 홈화면, 여행 게시판, 검색 화면,상세 화면 등 API 연결 ( 대부분의 여행 컨텐츠 get API response에 bookmarked :boolean 추가됨)
BoxLayout props 추가 & 하트 Icon <Link/>로 부터 종속하지 않도록 따로 버튼 형식을 추가함.
> feat: 북마크 내 여행 이외 모든 페이지에 연결 & 북마크가 들어가는 BoxLayout 조금 수정

- src/api/notification.ts
- src/api/search.ts
- src/components/Header.tsx
- src/hooks/notification/useNotification.ts
- src/pages/TripDetail/TripDetail.tsx
- src/pages/TripDetail/TripDetailHeader.tsx
> Fix: comment관련 변경

- src/hooks/enrollment/useEnrollment.ts
- src/pages/TripAcceptance/TripEnrollmentList.tsx
- src/utils/time.ts
- 첫 초기값이 null이므로, 컴포넌트에서 여행 생성 createdAt 값을 사용.
- 이후 컴포넌트 언마운트 시, put 요청으로 viewAt 업데이트.
> fix: lastViewed 신청 목록 조회 부분 null 초기값 문제, 수정

- src/hooks/user/useAuth.ts
- src/pages/MyPage/EditMyInfo.tsx
1. 리프레시 토큰에서 토큰이 없을 때 login으로 가는 onError 구문을 추가했고,
2. 로그아웃 실패 해도 로그인 페이지로 넘어가는 버그를 수정
> Fix: 리프레시토큰, 로그아웃 관련 수정

- src/api/enrollment.ts
- src/components/ButtonContainer.tsx
- src/components/designSystem/toastMessage/resultToast.tsx
- src/constants/errorMessages.ts
- src/hooks/enrollment/useEnrollment.ts
- src/pages/TripAcceptance/TripEnrollmentCard.tsx
- src/pages/TripAcceptance/TripEnrollmentList.tsx
- src/pages/TripDetail/TripDetail.tsx
- src/pages/TripDetail/TripDetailHeader.tsx
- src/utils/time.ts
- 여행 상세화면에서 주최자측만 신청자 목록 조회 가능 => 항상 get요청을 해서 주최자가 아닐때도 500에러를 만들어서 수정
- 컴포넌트 리펙토링. utils, 에러 메시지 분리
- 디자인 변경된 부분 반영.
> [여행 수락 신청 리펙토링 및 에러 부분 수정]

- src/pages/Register/RegisterTripStyle.tsx
tempName && name -> tempName ?? name
> Fix: registerTripstyle tempname 사용 방법 변경

- src/components/ButtonContainer.tsx
- src/components/Header.tsx
- src/components/designSystem/modal/CheckingModal.tsx
- src/components/designSystem/modal/EditAndDeleteModal.tsx
- src/components/designSystem/modal/NoticeModal.tsx
- src/components/designSystem/modal/ResultModal.tsx
- src/components/designSystem/toastMessage/resultToast.tsx
- src/pages/Community/Community.tsx
- src/pages/Home/Home.tsx
- src/pages/MyPage/EditMyInfo.tsx
- src/pages/MyPage/MyPage.tsx
- src/pages/MyTrip/HostTrip.tsx
- src/pages/MyTrip/MyTrip.tsx
- src/pages/TripDetail/TripDetail.tsx
- src/pages/TripList/TripList.tsx
- src/styles/palette.ts
- yarn.lock
- 헤더 padding 영역 통일!
- 토스트 메시지 색상 아이콘 색 변경
- popup(모달) 클릭시 배경색 변경 반영
- 수정 삭제 버튼 클릭시 배경색 변경 반영
- 마이페이지 일부 버튼들 클릭시 배경색 변경 반영
- 하단 버튼은 일부 반영.
> fix: QA사항 반영 + 일부 디자인 시스템 반영

- src/components/TopModal.tsx
환경에 따라 높이 측정 뒤 max-height 지정,
overflow: hidden 추가
> Fix: 여행 상세 탑컨텐츠 디자인 수정

- src/page/Home/Navbar.tsx
- src/page/MyCommunities.tsx
- src/page/MyPage/MyPage.tsx
- src/page/TripAcceptance/TripEnrollmentList.tsx
- 마이페이지 작성한 글 0개일 때 화면 추가
- 작성한 글 페이지에서 nav 메뉴 아이콘 활성화 안된 부분 수정
- 신청자 목록 조회 흰화면 문제 수정
- 마이페이지에서 유저의 태그 길이가 긴 경우, 부모 바깥으로 나가는 문제 수장
> [QA - 마이페이지, 참가 신청자 목록 조회 등]

- src/page/MyPage/EditMyInfo.tsx
- click handler 를 로그아웃 버튼에만 두는 것으로 수정
> fix: 탈퇴하기 누르면 > 로그아웃 모달뜨는 문제 해결

- src/components/TopModal.tsx
- src/components/designSystem/toastMessage/tripToast.tsx
- src/page/CreateTrip/CreateTripDetail/CreateTripDetail.tsx
- src/page/TripDetail/TripDetail.tsx
- src/page/TripDetail/TripEdit.tsx
테스트 완료했고, 토스트 클릭 부분에서 버그가 있길래 수정
> Fix: 버그 수정

- src/components/TopModal.tsx
테스트 완료했고, 토스트 클릭 부분에서 버그가 있길래 수정
> Fix: 스와이프 새로고침 방지 테스트

- src/styles/globalStyle.ts
> Fix: 스와이프 새로고침 막기

- src/app/globals.css
> Fix: 스와이프 새로고침 막기2

- src/components/designSystem/toastMessage/WarningToast.tsx
- src/page/MyPage/EditMyTag.tsx
- 경고용 토스트 컴포넌트 추가
- 5개 넘개 선택할 경우 => "최대 5개까지 설정할 수 있어요" 토스트가 생기도록 수정.
> fix: 마이페이지 태그 수정 페이지 -  최대 5개 이상 태그 설정 가능한 문제관련 토스트 추가 요청 반영

- src/components/designSystem/Select.tsx
> Fix: select 부분 수정

- src/page/Report/ReportDetail.tsx
> Fix: 신고하기 id 잘못 넣었음

- src/page/Report/Report.tsx
- src/page/Report/ReportDetail.tsx
> Fix: 신고하기 id 잘못 넣었음2

- src/components/designSystem/modal/NoticeModal.tsx
> Fix: 신고 완료 모달 portal로 빼기

- src/api/index.ts
> Fix: 헤더 바꿔보기

- src/api/index.ts
> Fix: 콘솔찍기"

- src/api/index.ts
> Fix: retry삭제

- src/components/Layout.tsx
- src/components/map/GoogleMap.tsx
- src/components/map/KakaoMap.tsx
- src/page/CreateTrip/CreateTripDetail/CalendarWrapper.tsx
- src/page/CreateTrip/CreateTripDetail/CreateTripDetail.tsx
- src/page/CreateTrip/CreateTripDetail/InfoWrapper.tsx
- src/page/CreateTrip/CreateTripDetail/RecruitingWrapper.tsx
- src/page/CreateTrip/CreateTripDetail/TagListWrapper.tsx
- src/page/CreateTrip/CreateTripTag.tsx
- src/page/TripDetail/TripDetail.tsx
> 여행 생성 파트 디자인 QA 수정

- src/components/Header.tsx
- src/components/map/GoogleMap.tsx
- src/components/map/KakaoMap.tsx
> Fix: 배경색 변경한 페이지 header와 동기화 및 지도 스크롤 막는 것 wheel 이벤트로 바꾸기

- src/components/Header.tsx
- src/page/CreateTrip/CreateTripDetail/CreateScheduleItem.tsx
- src/page/CreateTrip/CreateTripDetail/CreateTripDetail.tsx
- src/page/CreateTrip/CreateTripDetail/search/SearchPlaceDetail.tsx
- src/page/TripDetail/TripEdit.tsx
- src/store/client/tripPlanStore.ts
- 여행 수정시 원 데이터 수정 페이지에서 api 요청으로 가져오도록 변경
- 일정 검색 상세 부분에서 카카오 지도 부분 주소 필드 변경
- 일정 생성 후 돌아왔을 때 페이지 스크롤 이동
> 여행 수정 관련 변경

- src/page/MyPage/MyPage.tsx
> fix: 마이페이지 게스트 유저 화면 수정

- src/components/userProfile/UserProfileDetail.tsx
- src/page/UserProfileBadge/UserProfileBadge.tsx
> fix: 여행 뱃지 개수 임시 데이터 넣은 부분 => 수정

- src/components/icons/ProfileRightVectorIcon.tsx
- src/components/userProfile/UserProfileDetail.tsx
> design: > 아이콘 수정

- src/components/userProfile/UserProfileDetail.tsx
> design: 마이페이지 아이콘 세로축 정렬

- src/api/tripDetail.ts
- src/hooks/userProfile/moveToUserProfilePage.ts
> fix: moveToUserProfilePage use client 추가(최종)

- src/api/tripDetail.ts
- src/hooks/userProfile/moveToUserProfilePage.ts
> #76 
>
[ ] 커밋 메시지 컨벤션에 맞게 작성했습니다.
> Fix: moveToUserProfilePage store 함수 안으로 넣기

- src/components/comment/Comment.tsx
- src/hooks/userProfile/moveToUserProfilePage.ts
- src/page/TripDetail/TripDetail.tsx
#76 
>
[ ] 커밋 메시지 컨벤션에 맞게 작성했습니다.
> Fix: moveToUserProfilePage 컴포넌트에서 호출하도록 변경

- src/api/tripDetail.ts
- src/api/user.ts
> Fix: api 호출 에러 수정

- src/api/user.ts
>  #511 
>
[ ] 커밋 메시지 컨벤션에 맞게 작성했습니다.
> Fix: 오타 수정

- src/components/userProfile/UserProfileOverlay.tsx
- src/components/userProfile/UserTravelTabMenu.tsx
상대방 프로필 조회 화면 height 수정 
추가로, 참가한 여행 과 만든 여행 요청에 대한 응답이 없을 시, 임시 화면 반환하는 것으로 수정
>
> fix: 상대방 프로필 조회 화면 height 수정

- src/components/community/CommunityPost.tsx
- src/components/userProfile/UserProfileOverlay.tsx
- src/components/userProfile/UserTravelTabMenu.tsx
- src/page/TripDetail/TripDetail.tsx
76
- 상대방 프로필 화면 UI 수정.
- 커뮤니티 작성자 프로필 누르면 상대방 프로필 조회 모달이 뜨도로 수정.
>
> fix : 상대방 프로필 화면 UI 수정 (여행 상세 댓글 버튼 z-index 낮추기 & 애니메이션 수정)

- src/components/userProfile/UserProfileOverlay.tsx
> design: 모바일 화면에서 화면 좁아지는 부분 width줘서 해결

- src/hooks/useHeaderNavigation.tsx
> fix - 로그화면, 뱃지 화면에서 뒤로가기시, 상대방프로필 모달이 보이도록 수정

- src/components/travellog/AreaDropdown.tsx
> Fix: VisitContainer에서 다녀온 여행 날짜 다 안보이는 부분 수정

- src/hooks/useHeaderNavigation.tsx
> fix: 여행 뱃지, 로그 화면 에서 뒤로가기시, 모달 보이도록 수정 setTimeout텀 추가. 한번에 바로 뒤로가는 문제 수정

- src/api/userProfile.ts
> fix: API URL 변경

- src/components/userProfile/UserProfileOverlay.tsx
- src/components/userProfile/UserProfileOverlayHeader.tsx
- src/components/userProfile/UserTravelTabMenu.tsx
- 탭 메뉴를 클릭할 때 마다, height를 조절하는 것으로 수정
>
> fix & design: 상대방 프로필 모달 height 동적 조절 수정

- src/utils/travellog/travelLog.ts
> fix: 다녀온 여행 국내 부분 타입 안정화

- src/components/userProfile/UserTravelTabMenu.tsx
> fix: 상대방 프로필 조회 데이터가 없을 때 화면이 나오지 않는 문제 수정중

- src/components/userProfile/UserTravelTabMenu.tsx
> fix: 상대방 프로필 조회 - 참가한 여행 또는 만든 여행 count 0일 때, 대체 화면 가려지는 문제 수정"

- src/components/userProfile/UserProfileOverlay.tsx
- src/components/userProfile/UserTravelTabMenu.tsx
- margin, 최소 조회 모달의 height를 변경
>
> fix&design: 상대방 프로필 조회, 참가한 여행 신청한 여행 데이터 0개 일 때 화면 수정

- src/app/globals.css
- 홈화면 가로축 스크롤 생기는 부분도 같이 수정됨
- 많은 여행이 리스트에 있는 경우, 자동으로 아래로 스크롤 내려가는 부분도 같이 수정.
>
> fix: 상대방 프로필 가로축 스크롤이 생기는 부분 수정

- src/components/userProfile/UserProfileOverlay.tsx
> fix&Design : 모바일 화면에서 스크롤 중간쯤 튕기를 문제 수정
